import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <main className="bg-gray-50">
          <div className={false ?"mx-auto p-2 md:p-6": ""}>
            <div className="flex bg-gray-50">
              {/* Sidebar */}
              <Sidebar/>
              {/* Main content */}
              <div className="flex-1 overflow-auto">
                <div className="p-4 sm:p-8 space-y-6">{children}</div>
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
